services:
  iot-backend:
    build: ./backend
    ports:
      - "8000:8000"
   
    volumes:
      - ./backend/app:/code/app
    command: ["fastapi", "run", "app/main.py", "--reload","--host", "0.0.0.0", "--port", "8000"]
  iot-device:
    build: ./devices
    environment:
      - INGEST_URL=http://iot-backend:8000/ingest
    command: ["python", "temperature.py", "--device-id", "device_1"]
    depends_on:
      - iot-backend