services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    develop: 
      watch:
        - action: sync
          path: ./backend/app
          target: /code/app
    command: ["fastapi", "run", "app/main.py","--reload", "--port", "8000"]
    depends_on:
      db:
        condition: service_healthy
  iot-device:
    build: ./devices
    environment:
      - INGEST_URL=http://backend:8000/ingest
      - REGISTER_URL=http://backend:8000/devices
    command: ["python", "temperature.py", "--device-id", "device_1"]
    depends_on:
      - backend
    develop: 
      watch:
        - action: sync+restart
          path: ./devices/
          target: ./code/
  db:
    image: postgres:18
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports: 
    - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db-data: